server:
  port: 8080

# 数据源配置、dubbo相关配置等
spring:
  profiles:
    active: ${env}
    include: dubbo, jdbc, redis

# 日志相关配置
logging:
  config: classpath:logback.xml
  path: ./
  level: debug
  immediate:
    flush: true

mybatis:
  mapper-locations: "classpath*:/mapper/*Mapper.xml"
  typeAliasesPackage: com.mogu.demo.mapper